---
# vim: set ft=ansible et ts=2 sw=2:
#
# Create a new VM from a template using the new vmware_guest module
- name: Create virtual machine
  hosts: localhost
  gather_facts: True
  connection: local
  user: remote
  
  vars:
    vcenter_hostname: 'ukrdvmgvc001.dbpoc.uk'
    esxi_host: 'ukrdsesxi001.dbpoc.uk'
    datacenter: 'Reading-Dev'
    datastore: 'ukrd_esx_mgmt_data_001'
    network: 'DMZ_Internet_Vlan201'
    vmtemplate: 'Template-Centos7'
    vmcluster: 'Reading-Dev-PoC'
    notes: 'Created by Jeff Ansible 01'
    vcenter_folder: 'Reading-Dev'
    disk: '10'
    memory: '256'
    cpucount: '1'
    osid: 'ubuntu64Guest'
    dumpfacts: False
  tasks:
    - name: Check for required variables
      fail: msg="Must pass name and group to -e"
      when: name is not defined or group is not defined
      
    - name: Check for vSphere access parameters
      fail: msg="Must set vcenter_user and vcenter_pass in a Vault"
      when: (vcenter_user is not defined) or (vcenter_pass is not defined)
        
    - name: Create VM from template
      vmware_guest:
        validate_certs: False
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        esxi_hostname: "{{ esxihost }}"
        datacenter: "{{ datacenter }}"
        name: "{{ name }}"
        state: present
        template: "{{ vmtemplate }}"
        vm_extra_config:
          notes: "{{ notes }}"
 #        folder: "{{ vcenter_folder }}"
        disk:
          - size_gb: "{{ disk }}"
            type: thin
            datastore: "{{ datastore }}"
        nic:
          - type: vmxnet3
            network: "{{ network }}"
            network_type: "standard"
        hardware:
          memory_mb: "{{ memory | default(1024) }}"
          num_cpus: "{{ cpucount }}"
          osid: "{{ osid }}"
          scsi: "paravirtual"        
        esxi:
          datacenter: "{{ datacenter }}"
hostname: "{{ esxi_host }}" 
